-- Role IDs
SE_CAPTAIN = 1
SE_ENGINEER = 2
SE_SCIENTIST = 3
SE_PILOT = 4
SE_WEAP_SPEC = 5

-- Body types.
BODY_TYPE_STAR = 1
BODY_TYPE_ASTEROID = 2
BODY_TYPE_STATION = 3
BODY_TYPE_PLANET = 4

-- Game states. NONE means that game is not started(No players connected)
SE_STATE_NONE = 0
SE_STATE_PLAY = 1
SE_STATE_BATTLE = 2
SE_STATE_DEATH = 3

-- Ship types. Unused for now
SE_SHIP_EXPLORER = 0


SE_ASTEROID_SMALL = 0
SE_ASTEROID_MEDIUM = 1
SE_ASTEROID_BIG = 2


SE_PLANET_EARTHLIKE = 1
SE_PLANET_DUST = 2
SE_PLANET_FROZEN = 3
SE_PLANET_GAS = 4
